// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5o4VRywQvHccyhOwGvKm2E-O2L5sDs14',
    appId: '1:963667972498:web:61124f9631bb7a01ac314b',
    messagingSenderId: '963667972498',
    projectId: 'emeritmonitor',
    authDomain: 'emeritmonitor.firebaseapp.com',
    storageBucket: 'emeritmonitor.firebasestorage.app',
    measurementId: 'G-Q6HPDZC0FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRetFHXDUmLaRZ2ccNFEmwlGgH1CbVpA0',
    appId: '1:963667972498:android:ba5aee5c4d66be02ac314b',
    messagingSenderId: '963667972498',
    projectId: 'emeritmonitor',
    storageBucket: 'emeritmonitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAONuAzb5fmix4-WW50QigL-sjjXHWcLL4',
    appId: '1:963667972498:ios:7c2bac7c1db31cb9ac314b',
    messagingSenderId: '963667972498',
    projectId: 'emeritmonitor',
    storageBucket: 'emeritmonitor.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAONuAzb5fmix4-WW50QigL-sjjXHWcLL4',
    appId: '1:963667972498:ios:7c2bac7c1db31cb9ac314b',
    messagingSenderId: '963667972498',
    projectId: 'emeritmonitor',
    storageBucket: 'emeritmonitor.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5o4VRywQvHccyhOwGvKm2E-O2L5sDs14',
    appId: '1:963667972498:web:93a33822b6ae91c6ac314b',
    messagingSenderId: '963667972498',
    projectId: 'emeritmonitor',
    authDomain: 'emeritmonitor.firebaseapp.com',
    storageBucket: 'emeritmonitor.firebasestorage.app',
    measurementId: 'G-NL38YZP1BC',
  );

}